name: "Build Docker Images"
on:
  pull_request:
    branches:
      - main
  push:

jobs:
  build-bot-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate X509 certificate for testing
        run: scripts/generate_x509.sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: bot/.

  build-db-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate X509 certificate for testing
        run: scripts/generate_x509.sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: db/.
